# Generated by Django 2.2.14 on 2023-11-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('info', models.CharField(max_length=100)),
            ],
        ),
    ]
