# Generated by Django 2.2.14 on 2023-11-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20231105_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firs_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('number', models.IntegerField(blank=True)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('budget', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(blank=True)),
                ('info', models.CharField(blank=True, max_length=100)),
                ('audio', models.CharField(blank=True, max_length=100)),
                ('video', models.CharField(blank=True, max_length=100)),
                ('staging', models.CharField(blank=True, max_length=100)),
                ('special', models.CharField(blank=True, max_length=100)),
                ('lighting', models.CharField(blank=True, max_length=100)),
                ('backline', models.CharField(blank=True, max_length=100)),
                ('crowd', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
