# Generated by Django 2.2.14 on 2023-11-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_quoteform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quoteform',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
